version: '3.8'

services:
  semeando-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: semeando-app
    restart: unless-stopped
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
